### PR TITLE
AllowTelemetry should be REG_DWORD

### PR DESCRIPTION
**Pull request by zy26**

### CODE REVIEW

**Comment by 10se1ucgo** [comment]
On my machine AllowTelemetry is a string (REG_SZ) not a DWORD.

**Comment by Ruined1** [comment]
Confirmed on my machine (64-bit Windows 10) as well...

AllowTelemetry is a string (REG_SZ) not a DWORD.

**Comment by 10se1ucgo** [comment]
Closing for now. Don't hesitate to reopen if you still think something is wrong.

**Comment by zy26** [comment]
I think your AllowTelemetry is a string (REG_SZ) because you have used DisableWinTracking before.

**Comment by zy26** [comment]
To reproduce default type of AllowTelemetry, please delete AllowTelemetry and change the Feedback frequency setting. 

>To change the Feedback frequency setting, go to Start Start icon, then select Settings > Privacy > Feedback & diagnostics, and then, under Feedback frequency, select an option.

http://windows.microsoft.com/en-us/windows-10/feedback-diagnostics-privacy-faq

**Comment by zy26** [comment]
You can also set the Feedback frequency setting to Never using the following command line:
```
SystemSettingsAdminFlows.exe FeedbackOptinLevel 0
```
It will change the type of AllowTelemetry to default one.

**Comment by 10se1ucgo** [comment]
Huh. You're right. This is super weird. When I started development AllowTelemetry was a string for me, but after using gpedit to set Allow Telemetry to "2" it changed the string into a dword... Pulling this.

**Pull request merged**
