### PR TITLE
Fix code style and implement disable Xbox DVR

### PR DESCRIPTION
**Pull request by molecul**
I am make a some fixes in code style (according with pep8) and implement disable Xbox DVR ability.

P.S: Users experiencing low FPS or FPS loss after upgrading to Windows 10 may resolve the issue by disabling the Xbox DVR feature.

### CODE REVIEW

**Comment by molecul** [comment]
Also update program screenshot

**Comment by molecul** [comment]
Done.

**Comment by Ruined1** [comment]
While this is more of a performance fix, and it's questionable whether it fits into the scope of this project, I am adding it as Digital Video Recording requires a buffer of the recorded screen, which some may see as a privacy violation. There are still conflicts that need to be addressed:

"This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch."

**Comment by molecul** [comment]
Moved to https://github.com/10se1ucgo/DisableWinTracking/pull/414

**Pull request closed without merging**
