### PR TITLE
Update to update code.

### LINKED ISSUE #264: DWT crashes on startup if there's no Internet access. Remove the automatic update check.
UPDATE months later: it appears that DMT is no longer maintained. I suggest people use Spybot Anti-beacon as a superior alternative, though it's not open-source. 

I have a fresh Win10 system, and I wanted to apply DWT before I connected it to the Internet, because I think it's smarter this way.

I copied the installer by USB key, but it won't run because there's no Internet. I get an exception as soon as I launch it. This is poorly thought-out.

EDIT because I see from a different issue that @10se1ucgo  is aware of the problem, but laughed it off. Here's why this should be fixed: by leaving the buggy update check, you force the user to connect to the Internet before they can disable the tracking. By doing this, the tracking services can upload all the information accumulated up to that point while offline. In other words, even if DWT stops *future* tracking, it helps Win10 report tracked data accumulated prior to its installation. This should be considered a critical flaw.

It's like changing the door on a barn, without tying the horse to a post first so he doesn't bolt. "Oh, this door is only for stopping future horses, sorry about the existing ones".

**INFORMATION:**

* Windows Edition (Home/Pro/Enterprise): Home
* Architecture (32bit/64bit): 64-bit
* Options used:

**LOG:**

```python
17:07:51 INFO: Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
17:07:51 INFO: ('Windows', 'DESKTOP-3VIFGI2', '10', '10.0.14393', 'AMD64', 'Intel64 Family 6 Model 69 Stepping 1, GenuineIntel')
17:07:51 INFO: DisableWinTracking version 3.0.1
17:07:52 CRITICAL: Traceback (most recent call last):
  File "dwt.py", line 440, in <module>
  File "dwt_about.py", line 170, in update_check
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 431, in open
  File "urllib2.py", line 449, in _open
  File "urllib2.py", line 409, in _call_chain
  File "urllib2.py", line 1240, in https_open
  File "urllib2.py", line 1197, in do_open
URLError: <urlopen error [Errno 11001] getaddrinfo failed>
```

### PR DESCRIPTION
**Pull request by Didey**
Adds try to urlopen call instead of just dialog box, fixes #264 and #230.

### CODE REVIEW

**Comment by 10se1ucgo** [comment]
`try`/`except` needs to be around `urlopen` ONLY. then, return early. don't use pass.

**Comment by Didey** [comment]
@10se1ucgo, if I remove everything that's not the URLOpen call you'll still get a nullreference exception, so it's better to have all the code in the catch, so there are no errors. Also, pass is used LITERALLY in the same function. Kinda confused here.

**Comment by manad777** [comment]
@10se1ucgo , it's a one-liner, please just change it yourself to how you want it,  we spent more time talking about it than it takes to actually do it :)

I got a Win10 PC and I'm waiting for this fix to put it on the network, any chance you could do the release ASAP?

**Comment by Didey** [comment]
I fixed it for @manad777 and @10se1ucgo. Now returns instead of pass, and only around the urlopen call.

**Comment by Ruined1** [comment]
@Didey looks good now, checked to make sure it met @10se1ucgo's requirements of you and merged it on his behalf

**Pull request merged**
