### PR TITLE
Optimization: Concentrated the 64-bit registry

### PR DESCRIPTION
**Pull request by Ruined1**
Optimization: Concentrated the 64-bit registry back into one function.

### CODE REVIEW

**Comment by 10se1ucgo** [comment]
If you look at the code I wrote, it only uses 64 bit for the WifiSense/Defender stuff if the machine is 64 bit.

You can test this with

```python
if platform.machine().endswith('64'):
    osis64bit = True
else:
    osis64bit = False
```

**Comment by Ruined1** [comment]
Right, but your method requires two functions, mine only requires one function to do both 32 and 64 bit, plus provides better logging In case we ever have problem with a dictionary now or in the future. I cutout to remove that extra piece of code, I'll do a commit now

**Comment by 10se1ucgo** [comment]
ahh I see now, this is good.

**Comment by Ruined1** [comment]
Yup looks good to me :sweat_smile: I hope I'm not being overbearing, I just want to help add to and optimize the code in every way I can. This is a wonderful project that the world truly needs, and I'm honored to be able to assist with it.

**Pull request merged**
