### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by Ruined1**
Finished Optimizing Registry Entries

Fixed a typo.

I hope this optimizes the code quite a bit. Should reduce filesize and (probably not noticeably) improve execution time. It should also provide an easy way to implement any registry changes in the future.

Please revise it carefully to make sure I didn't screw up :sweat_smile:

### CODE REVIEW

**Comment by Ruined1** [comment]
Also, I need help resolving the conflicts between my branch and your master. I still dont get how to do that...

**Comment by 10se1ucgo** [comment]
One slight problem as well, not every registry value is a REG_DWORD. AllowTelemetry is a REG_SZ (String value)

**Comment by Ruined1** [comment]
I'll be happy to fix that, however i need to figure out how to get the latest master merged without losing all my work. I pulled your master to ruined1:master then tried pulling ruined1:optimization to ruined1:master, but the same conflict exists. How do i solve this :tired_face:

**Comment by 10se1ucgo** [comment]
I have no clue either, not too familiar with git myself.

**Comment by 10se1ucgo** [comment]
Oh hey, its working. I can pull it now.

**Comment by 10se1ucgo** [comment]
I know you were still working on merging it and what not but don't worry I'll iron those out now.

**Pull request merged**
