### PR TITLE
Stop Windows Defender and WifiSense Datamining

### PR DESCRIPTION
**Pull request by Ruined1**
Add registry changes to Enable/Disable Windows Defender and WifiSense Datamining.

### CODE REVIEW

**Comment by 10se1ucgo** [comment]
Can you update your branch to be on level with mine so I can marge this?

**Comment by Ruined1** [comment]
Unfortunately I don't know how to do that yet... Still new with github, trying to figure out how to update my master to be in sync with your's so I can apply my changes to it to submit for a pull request

**Comment by 10se1ucgo** [comment]
What you can do if you don't want to merge is to just copy your version to a seperate location, download the latest from github and compare the 2 files to add your features back.

**Comment by Ruined1** [comment]
Scratch this one, I got your reply too late after I already re-forked the repository :sweat_smile:

**Pull request closed without merging**
