### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 4vanger**
Update a warning for cyrillic languages

### CODE REVIEW

**Comment by 10se1ucgo** [comment]
I don't speak any Slavic language so I'll just take your word for it :)

I should have a look into this problem, though.

**Comment by 4vanger** [comment]
Most likely there should be a function to get a UTF-8 encoded path. I assume there should be a problem with any non-ASCII pathes

**Comment by 10se1ucgo** [comment]
I'd imagine going back to Python 3 would certainly make this a lot easier. Previously, I was hesitant to as Python 3 had been causing a number of people to report that the pyinstaller package wasn't working (some error related to the wxWidgets DLLs not loading). I'll look into this whenever I get the chance.

**Comment by 4vanger** [comment]
Yeah, UTF-8 support in Python2 is pure disaster.

**Comment by 10se1ucgo** [comment]
Oh yeah. I've recently been doing C++ for a game and it's been a pain in the ass. I miss Python sometimes :'(

**Pull request merged**
